#!/usr/bin/env sh

CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)

if [ "$CURRENT_BRANCH" = "develop" ] || [ "$CURRENT_BRANCH" = "staging" ] || [ "$CURRENT_BRANCH" = "main" ]; then
  echo "🚨 Main branch detected ($CURRENT_BRANCH). Running full validations..."
  
  # 1. Run lint only on modified files (fast)
  echo "-> Running quick lint (lint-staged)..."
  npm exec -w app -- lint-staged  --relative || exit 1

  # 2. Run full lint across the workspace/app
  echo "-> Running full lint..."
  npm run lint -w app || exit 1

  # 3. Run type checking
  echo "-> Running Type check..."
  npm run type-check -w app || exit 1

  # 4. Run tests
  echo "-> Running Tests..."
  npm run test -w app || exit 1

else
  # This block only runs if the branch is NOT main, develop, or staging
  echo "🌱 Feature branch detected ($CURRENT_BRANCH). Running lint-staged only..."
  npm exec -w app -- lint-staged  --relative || exit 1
fi